name = "Orbit"
license = "MIT"
licenselink = "//github.com/aerohub/hugo-orbit-theme/blob/master/LICENSE.md"
description = "Responsive Resume/CV Theme for Developers and alike"
homepage = "//github.com/flavorplus/hugo-orbit-theme"
tags = ["cv", "resume", "colour schemes"]
features = ["responsive", "colour schemes"]
min_version = 0.16

[author]
  name = "Jonathan Vermeulen"
  homepage = "//github.com/flavorplus"

# If porting an existing theme
[original]
  name = "Pavel Kanyshev"
  homepage = "//github.com/aerohub"
